#!/bin/bash

# 彩色输出
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}================================${NC}"
echo -e "${BLUE}  Verdant Search Docker 部署${NC}"
echo -e "${BLUE}================================${NC}"
echo ""
echo -e "${GREEN}📦 已创建的文件：${NC}"
echo ""
echo "1. Dockerfile                 - 单容器 Dockerfile（包含所有服务）"
echo "2. .dockerignore             - Docker 构建忽略文件"
echo "3. docker-deploy.sh          - 自动化部署脚本"
echo "4. DOCKER_README.md          - 主要文档（一行命令启动）"
echo "5. DOCKER_DEPLOYMENT.md      - 完整部署文档"
echo "6. QUICK_START.md            - 快速启动指南"
echo ""
echo -e "${YELLOW}🚀 快速上手（三种方式）：${NC}"
echo ""
echo -e "${GREEN}方法 1：一行命令（最简单）${NC}"
echo "========================================"
echo 'docker build -t verdant-search . && docker run -d --name verdant-search -p 5173:5173 verdant-search && echo "访问 http://localhost:5173"'
echo ""
echo -e "${GREEN}方法 2：使用自动化脚本${NC}"
echo "========================================"
echo "./docker-deploy.sh"
echo ""
echo -e "${GREEN}方法 3：手动分步部署${NC}"
echo "========================================"
echo "# 步骤 1: 构建镜像"
echo "docker build -t verdant-search:latest ."
echo ""
echo "# 步骤 2: 运行容器"
echo "docker run -d --name verdant-search -p 5173:5173 verdant-search:latest"
echo ""
echo "# 步骤 3: 访问"
echo "open http://localhost:5173"
echo ""
echo -e "${BLUE}================================${NC}"
echo -e "${YELLOW}⏱️  预计时间：${NC}"
echo "  - 首次构建: 10-20 分钟"
echo "  - 首次启动: 60-90 秒"
echo "  - 后续启动: 10-20 秒"
echo ""
echo -e "${YELLOW}📚 文档说明：${NC}"
echo "  - DOCKER_README.md      → 主要文档（推荐先读这个）"
echo "  - QUICK_START.md        → 快速启动指南"
echo "  - DOCKER_DEPLOYMENT.md  → 详细部署文档"
echo ""
echo -e "${GREEN}✨ 特性：${NC}"
echo "  ✅ 单个容器包含所有服务（除爬虫）"
echo "  ✅ PostgreSQL 16 + pgvector"
echo "  ✅ Redis 缓存"
echo "  ✅ Python FastAPI 搜索引擎"
echo "  ✅ Go Gin 后端"
echo "  ✅ React 前端"
echo "  ✅ Supervisor 进程管理"
echo "  ✅ 自动重启和健康检查"
echo ""
echo -e "${BLUE}================================${NC}"
echo ""
