ALTER TABLE users
  ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(10) DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS results_per_page INTEGER DEFAULT 10,
  ADD COLUMN IF NOT EXISTS reranker_enabled BOOLEAN DEFAULT TRUE;
